# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'

target 'Hackathon2017' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hackathon2017
  pod 'IQKeyboardManagerSwift'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'GoogleMaps'

end
