version: '2'
services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile-web
    environment:
      - TZ=Europe/Warsaw
    ports:
      - "9990:9990"
      - "8080:8080"
      - "8787:8787"